export const awaitingConfirmationStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--color-grey-100)",
  },
  card: {
    maxWidth: "450px",
    width: "100%",
    padding: "var(--spacing-big)",
    backgroundColor: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
  },
  logoContainer: {
    textAlign: "center" as const,
    marginBottom: "1.5rem",
  },
  logo: {
    width: "80px",
    height: "auto",
  },
  title: {
    fontSize: "var(--font-size-big)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "0.5rem",
    color: "var(--color-warning)",
    textAlign: "center" as const,
  },
  subtitle: {
    color: "var(--color-grey-600)",
    textAlign: "center" as const,
    marginBottom: "1.5rem",
  },
  alertSuccess: {
    padding: "var(--spacing-small)",
    borderRadius: "var(--border-small-radius)",
    backgroundColor: "var(--color-success-light)",
    color: "var(--color-success-dark)",
    marginBottom: "var(--spacing-normal)",
  },
  alertError: {
    padding: "var(--spacing-small)",
    borderRadius: "var(--border-small-radius)",
    backgroundColor: "var(--color-error-light)",
    color: "var(--color-error-dark)",
    marginBottom: "var(--spacing-normal)",
  },
  buttonContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "var(--spacing-small)",
  },
  primaryButton: {
    width: "100%",
    padding: "0.5rem 1rem",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    borderRadius: "var(--border-small-radius)",
    border: "none",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  primaryButtonDisabled: {
    backgroundColor: "var(--color-grey-500)",
    cursor: "not-allowed",
  },
  secondaryButton: {
    width: "100%",
    padding: "0.5rem 1rem",
    backgroundColor: "var(--color-neutral)",
    color: "var(--color-text)",
    borderRadius: "var(--border-small-radius)",
    border: "none",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  footnote: {
    marginTop: "1.5rem",
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
    textAlign: "center" as const,
  },
};
