export const paymentStyles = {
  stripeBg: {
    minHeight: "80vh",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "var(--color-grey-100)",
  },
  paymentWrapper: {
    backgroundColor: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    boxShadow: "0 4px 24px rgba(30, 41, 59, 0.08)",
    padding: "2.5rem 2rem",
    maxWidth: "400px",
    width: "100%",
    margin: "0 auto",
  },
  paymentForm: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1.25rem",
  },
  formInput: {
    width: "100%",
    padding: "0.75rem 1rem",
    borderRadius: "var(--border-small-radius)",
    border: "var(--border-width) solid var(--color-grey-400)",
    backgroundColor: "var(--color-white)",
    color: "var(--color-text)",
    fontSize: "var(--font-size-normal)",
    outline: "none",
    transition: "var(--animation-transition)",
  },
  payButton: {
    width: "100%",
    padding: "0.75rem 1.5rem",
    background: "linear-gradient(90deg, #3b82f6 0%, #6366f1 100%)",
    color: "var(--color-white)",
    fontWeight: "var(--font-weight-medium)",
    fontSize: "var(--font-size-normal)",
    borderRadius: "var(--border-small-radius)",
    border: "none",
    cursor: "pointer",
    transition: "var(--animation-transition)",
    marginTop: "0.5rem",
    opacity: 1,
  },
  payButtonHover: {
    background: "#2563eb",
  },
  errorMessage: {
    backgroundColor: "var(--color-grey-200)",
    color: "var(--color-black)",
    padding: "0.75rem 1rem",
    borderRadius: "var(--border-small-radius)",
    marginBottom: "0.5rem",
    fontSize: "var(--font-size-small)",
    textAlign: "center" as const,
  },
};
