export const dashboardStyles = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "var(--spacing-big)",
  },
  section: {
    marginBottom: "2.5rem",
  },
  sectionTitle: {
    fontSize: "var(--font-size-big)",
    color: "var(--color-text)",
    marginBottom: "1.2rem",
    display: "flex",
    alignItems: "center",
    borderBottom: "var(--border-width) solid var(--color-grey-400)",
    paddingBottom: "0.75rem",
  },
  sectionIcon: {
    marginRight: "0.75rem",
    color: "var(--color-blue)",
  },
  userInfoCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "1.5rem",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
  },
  avatar: {
    width: "100px",
    height: "100px",
    borderRadius: "var(--border-circle-radius)",
    background: "var(--color-blue)",
    color: "var(--color-white)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "2.5rem",
    fontWeight: "var(--font-weight-bold)",
  },
  userName: {
    margin: "var(--spacing-normal) 0",
    color: "var(--color-text)",
  },
  infoItem: {
    display: "flex",
    alignItems: "center",
    margin: "0.5rem 0",
  },
  infoIcon: {
    marginRight: "0.5rem",
    color: "var(--color-blue)",
  },
  companyCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "1.5rem",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
  },
  companyTitle: {
    color: "var(--color-text)",
    marginBottom: "var(--spacing-normal)",
  },
  companyDescription: {
    color: "var(--color-grey-600)",
    marginBottom: "1.5rem",
  },
  companyDetails: {
    marginTop: "var(--spacing-normal)",
    borderTop: "var(--border-width) solid var(--color-grey-400)",
    paddingTop: "var(--spacing-normal)",
  },
  teamGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "1.5rem",
  },
  teamCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "1.5rem",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    display: "flex",
    flexDirection: "column" as const,
  },
  teamTitle: {
    color: "var(--color-text)",
    marginBottom: "0.75rem",
  },
  teamDescription: {
    color: "var(--color-grey-600)",
    marginBottom: "var(--spacing-normal)",
    flexGrow: 1,
  },
  teamMeta: {
    margin: "var(--spacing-normal) 0",
  },
  leaderBadge: {
    background: "var(--color-blue)",
    color: "var(--color-white)",
    padding: "0.5rem",
    borderRadius: "var(--border-small-radius)",
    marginTop: "0.75rem",
    fontSize: "0.9rem",
    textAlign: "center" as const,
  },
  viewDetailsBtn: {
    background: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    padding: "0.75rem 1rem",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    marginTop: "auto",
    transition: "var(--animation-transition)",
    "&:hover": {
      background: "var(--color-blue-dark)",
    },
  },
  createCompanyBtn: {
    background: "var(--color-green)", // Couleur verte pour "créer"
    color: "var(--color-white)",
    border: "none",
    padding: "0.75rem 1rem",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "var(--animation-transition)",
    minWidth: "200px",
    "&:hover": {
      background: "var(--color-green-dark)",
    },
  },
  manageCompanyBtn: {
    background: "var(--color-blue)", // Couleur bleue pour "gérer"
    color: "var(--color-white)",
    border: "none",
    padding: "0.75rem 1rem",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "var(--animation-transition)",
    minWidth: "200px",
    "&:hover": {
      background: "var(--color-blue-dark)",
    },
  },
  manageTeamsBtn: {
    background: "var(--color-orange)", // Couleur orange pour "gérer les équipes"
    color: "var(--color-white)",
    border: "none",
    padding: "0.75rem 1rem",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    transition: "var(--animation-transition)",
    minWidth: "200px",
    "&:hover": {
      background: "var(--color-orange-dark)",
    },
  },
  btnIcon: {
    marginRight: "0.5rem",
  },
  loadingSpinner: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "50vh",
    fontSize: "1.2rem",
    color: "var(--color-blue)",
  },
  errorMessage: {
    background: "var(--color-error-light)",
    color: "var(--color-error-dark)",
    padding: "var(--spacing-normal)",
    borderRadius: "var(--border-small-radius)",
    margin: "2rem auto",
    maxWidth: "800px",
    textAlign: "center" as const,
  },
  actionsContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  noCompanyText: {
    color: "var(--color-grey-600)",
    fontSize: "1.1rem",
    textAlign: "center" as const,
    margin: "1rem 0",
  },
  noTeamsText: {
    color: "var(--color-grey-600)",
    fontSize: "1.1rem",
    textAlign: "center" as const,
    padding: "1.5rem",
    background: "var(--color-grey-100)",
    borderRadius: "var(--border-radius)",
  },
};
