export const confirmEmailStyles = {
  container: {
    minHeight: "100vh",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--color-grey-100)",
  },
  card: {
    maxWidth: "450px",
    width: "100%",
    padding: "var(--spacing-big)",
    backgroundColor: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    boxShadow: "0 1px 3px 0 rgba(0, 0, 0, 0.1)",
  },
  iconContainer: {
    marginBottom: "var(--spacing-normal)",
    textAlign: "center" as const,
  },
  loadingIcon: {
    height: "3rem",
    width: "3rem",
    borderRadius: "var(--border-circle-radius)",
    border: "var(--border-big-width) solid var(--color-grey-400)",
    borderTopColor: "var(--color-blue)",
    animation: "spin var(--animation-transition-time) linear infinite",
    margin: "0 auto",
  },
  successIcon: {
    height: "3rem",
    width: "3rem",
    margin: "0 auto",
    color: "var(--color-green)",
  },
  errorIcon: {
    height: "3rem",
    width: "3rem",
    margin: "0 auto",
    color: "var(--color-red)",
  },
  headingSuccess: {
    fontSize: "var(--font-size-big)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "0.5rem",
    color: "var(--color-green)",
    textAlign: "center" as const,
  },
  headingError: {
    fontSize: "var(--font-size-big)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "0.5rem",
    color: "var(--color-red)",
    textAlign: "center" as const,
  },
  headingLoading: {
    fontSize: "var(--font-size-big)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "0.5rem",
    color: "var(--color-blue)",
    textAlign: "center" as const,
  },
  message: {
    color: "var(--color-grey-600)",
    textAlign: "center" as const,
  },
  redirectMessage: {
    marginTop: "var(--spacing-normal)",
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
    textAlign: "center" as const,
  },
  button: {
    width: "100%",
    marginTop: "1.5rem",
    padding: "0.5rem 1rem",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    borderRadius: "var(--border-small-radius)",
    border: "none",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
};
