import { CSSProperties } from "react";

export const AuthStyles: Record<string, CSSProperties> = {
  logoWrapper: {
    position: "absolute",
    zIndex: 2,
  },
  logo: {
    objectFit: "contain",
    margin: "15px",
  },
  textWrapper: {
    position: "absolute",
    bottom: "80px",
    left: "0",
    background: "rgba(248, 248, 255, 0.1)",
    backdropFilter: "blur(10px)",
    padding: "24px 32px",
    borderRadius: "0 16px 16px 0",
    zIndex: 2,
  },
  title: {
    margin: 0,
    fontSize: "42px",
    color: "rgba(248, 248, 255, 0.9)",
    fontWeight: "600",
    letterSpacing: "0.5px",
  },
  subtitle: {
    margin: "4px 0 0 0",
    color: "rgba(248, 248, 255, 0.7)",
    fontSize: "14px",
    fontWeight: "400",
  },
  formContainer: {
    position: "absolute",
    right: "0",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(42, 47, 53, 0.95)",
    padding: "48px 40px",
    width: "400px",
    borderRadius: "24px 0 0 24px",
    backdropFilter: "blur(10px)",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.2)",
  },
  wrapper: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "20px",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    gap: "16px",
  },
  inputContainer: {
    width: "100%",
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  logoInput: {
    position: "absolute",
    left: "16px",
    zIndex: 2,
    opacity: 0.6,
  },
  input: {
    width: "100%",
    height: "46px",
    fontSize: "15px",
    padding: "0 44px",
    backgroundColor: "rgba(248, 248, 255, 0.08)",
    border: "1px solid rgba(248, 248, 255, 0.1)",
    borderRadius: "12px",
    color: "#f8f8ff",
    outline: "none",
    transition: "all 0.2s ease",
  },
  primaryButton: {
    width: "100%",
    height: "46px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "15px",
    fontWeight: "600",
    color: "#f8f8ff",
    backgroundColor: "#4999D7",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    transition: "all 0.2s ease",
    marginTop: "8px",
  },
  loginOther: {
    width: "100%",
    textAlign: "center",
    color: "rgba(248, 248, 255, 0.4)",
    fontSize: "13px",
    position: "relative",
    margin: "16px 0",
  },
  googleButton: {
    width: "100%",
    height: "46px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "#f8f8ff",
    border: "none",
    borderRadius: "12px",
    cursor: "pointer",
    fontSize: "15px",
    fontWeight: "500",
    color: "#2a2f35",
    transition: "all 0.2s ease",
  },
  imageWrapper: {
    position: "relative",
    width: "80%",
    height: "97vh",
    borderRadius: "50px",
    overflow: "hidden",
  },
  image: {
    objectFit: "cover",
    width: "100%",
    height: "100%",
    borderRadius: "40px",
  },
};
