// src/styles/pages/dashboard/manage/company/companyDetailsStyles.ts
export const companyDetailsStyles = {
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "1.5rem",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
  },
  pageTitle: {
    fontSize: "1.75rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  pageSubtitle: {
    fontSize: "1rem",
    fontWeight: "400",
    color: "var(--color-grey-600, #666)",
    marginTop: "0.375rem",
  },
  buttonContainer: {
    display: "flex",
    gap: "0.75rem",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 2fr",
    gap: "2rem",
    alignItems: "start",
  },
  leftPanel: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2rem",
  },
  rightPanel: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "2rem",
  },
  card: {
    background: "var(--color-white, #fff)",
    borderRadius: "0.5rem",
    padding: "1.5rem",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.05)",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    fontSize: "1.25rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
  },
  sectionIcon: {
    color: "var(--color-blue, #1976d2)",
    fontSize: "1.5rem",
  },
  companyHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  companyLogo: {
    width: "6.25rem",
    height: "6.25rem",
    borderRadius: "0.5rem",
    objectFit: "contain" as const,
    backgroundColor: "var(--color-grey-100, #f8f9fa)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "1.5rem",
  },
  companyLogoPlaceholder: {
    width: "6.25rem",
    height: "6.25rem",
    borderRadius: "0.5rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--color-grey-100, #f8f9fa)",
    color: "var(--color-blue, #1976d2)",
    fontSize: "2.5rem",
    marginRight: "1.5rem",
  },
  companyInfo: {
    flex: 1,
  },
  companyName: {
    fontSize: "1.5rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    marginBottom: "0.5rem",
  },
  companyIndustry: {
    fontSize: "1rem",
    color: "var(--color-grey-600, #666)",
    marginBottom: "0.75rem",
  },
  badgeContainer: {
    display: "flex",
    gap: "0.75rem",
  },
  statusBadge: {
    display: "inline-block",
    borderRadius: "0.375rem",
    padding: "0.375rem 0.75rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "var(--color-white, #fff)",
  },
  companyDescription: {
    color: "var(--color-grey-700, #555)",
    lineHeight: "1.6",
    margin: "1.5rem 0",
  },
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "1.5rem",
    margin: "1.5rem 0",
  },
  detailItem: {
    marginBottom: "1rem",
  },
  detailLabel: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
    marginBottom: "0.375rem",
    display: "flex",
    alignItems: "center",
    gap: "0.375rem",
  },
  detailValue: {
    fontSize: "1rem",
    color: "var(--color-text, #333)",
    fontWeight: "500",
  },
  divider: {
    height: "1px",
    backgroundColor: "var(--color-grey-400, #ccc)",
    margin: "1.5rem 0",
  },
  managerCard: {
    display: "flex",
    alignItems: "center",
    padding: "1.25rem",
    borderRadius: "0.5rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "var(--color-grey-100, #f8f9fa)",
      transform: "translateY(-3px)",
      boxShadow: "0 5px 15px rgba(0, 0, 0, 0.05)",
    },
  },
  managerAvatar: {
    width: "3.5rem",
    height: "3.5rem",
    borderRadius: "50%",
    backgroundColor: "var(--color-blue, #1976d2)",
    color: "var(--color-white, #fff)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "1.5rem",
    fontWeight: "600",
    marginRight: "1rem",
  },
  managerInfo: {
    flex: 1,
  },
  managerName: {
    fontSize: "1.125rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    marginBottom: "0.25rem",
  },
  managerEmail: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
    marginBottom: "0.25rem",
  },
  managerRole: {
    display: "inline-block",
    fontSize: "0.75rem",
    fontWeight: "500",
    color: "var(--color-white, #fff)",
    backgroundColor: "var(--color-blue, #1976d2)",
    padding: "0.25rem 0.5rem",
    borderRadius: "0.375rem",
    textTransform: "capitalize" as const,
  },
  teamsContainer: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "1rem",
    marginTop: "1rem",
  },
  teamItem: {
    display: "flex",
    alignItems: "center",
    padding: "1rem",
    borderRadius: "0.5rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    cursor: "pointer",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "var(--color-grey-100, #f8f9fa)",
      transform: "translateY(-3px)",
      boxShadow: "0 5px 15px rgba(0, 0, 0, 0.05)",
    },
  },
  teamIcon: {
    fontSize: "1.5rem",
    color: "var(--color-blue, #1976d2)",
    marginRight: "1rem",
  },
  teamInfo: {
    flex: 1,
  },
  teamName: {
    fontSize: "1rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    marginBottom: "0.25rem",
  },
  teamMemberCount: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
  },
  noDataCard: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem 1.5rem",
    textAlign: "center" as const,
  },
  noDataIcon: {
    fontSize: "3rem",
    color: "var(--color-grey-500, #999)",
    marginBottom: "1rem",
  },
  noDataText: {
    fontSize: "1rem",
    color: "var(--color-grey-600, #666)",
    marginBottom: "1.5rem",
  },
  tableContainer: {
    overflowX: "auto" as const,
  },
  table: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "0.9375rem",
  },
  tableHead: {
    backgroundColor: "var(--color-grey-100, #f8f9fa)",
  },
  tableHeader: {
    padding: "1rem",
    textAlign: "left" as const,
    fontWeight: "600",
    color: "var(--color-grey-700, #555)",
    borderBottom: "1px solid var(--color-grey-400, #ccc)",
  },
  tableRow: {
    borderBottom: "1px solid var(--color-grey-400, #ccc)",
    transition: "background-color 0.2s",
    "&:hover": {
      backgroundColor: "var(--color-grey-100, #f8f9fa)",
    },
  },
  tableCell: {
    padding: "1rem",
    color: "var(--color-text, #333)",
    whiteSpace: "nowrap" as const,
  },
  tableCellActions: {
    padding: "0.5rem 1rem",
    textAlign: "right" as const,
  },
  pagination: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 0",
    marginTop: "1.5rem",
  },
  paginationInfo: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  paginationButton: {
    padding: "0.5rem 0.75rem",
    backgroundColor: "var(--color-white, #fff)",
    color: "var(--color-text, #333)",
    border: "1px solid var(--color-grey-400, #ccc)",
    borderRadius: "0.375rem",
    cursor: "pointer",
    transition: "all 0.2s ease",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "0.875rem",
    "&:hover": {
      backgroundColor: "var(--color-grey-100, #f8f9fa)",
    },
    "&:disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  paginationButtonActive: {
    backgroundColor: "var(--color-blue, #1976d2)",
    color: "var(--color-white, #fff)",
    borderColor: "var(--color-blue, #1976d2)",
  },
  paginationPageNumbers: {
    display: "flex",
    gap: "0.25rem",
  },
  pageItemsSelector: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
  },
  pageItemsSelect: {
    padding: "0.375rem 0.5rem",
    borderRadius: "0.375rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    backgroundColor: "var(--color-white, #fff)",
    fontSize: "0.875rem",
  },
};
