// src/styles/pages/dashboard/admin/userDetailsStyles.ts
export const userDetailsStyles = {
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "1.5rem",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "2rem",
  },
  pageTitle: {
    fontSize: "1.75rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    display: "flex",
    alignItems: "center",
    gap: "1rem",
  },
  pageSubtitle: {
    fontSize: "1rem",
    fontWeight: "400",
    color: "var(--color-grey-600, #666)",
    marginTop: "0.375rem",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 2fr",
    gap: "2rem",
    alignItems: "start",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "1rem",
  },
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "0.75rem",
    fontSize: "1.125rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
  },
  sectionIcon: {
    color: "var(--color-blue, #1976d2)",
    fontSize: "1.375rem",
  },
  card: {
    background: "var(--color-white, #fff)",
    borderRadius: "0.5rem",
    padding: "1.5rem",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.05)",
    marginBottom: "2rem",
  },
  profileHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: "1.5rem",
  },
  avatar: {
    width: "6.25rem",
    height: "6.25rem",
    borderRadius: "50%",
    backgroundColor: "var(--color-blue, #1976d2)",
    color: "var(--color-white, #fff)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "2.25rem",
    fontWeight: "600",
    marginRight: "1.5rem",
  },
  profileInfo: {
    flex: 1,
  },
  profileName: {
    fontSize: "1.5rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    marginBottom: "0.375rem",
  },
  profileEmail: {
    fontSize: "1rem",
    color: "var(--color-grey-600, #666)",
    marginBottom: "0.75rem",
  },
  profileBadges: {
    display: "flex",
    gap: "0.75rem",
  },
  roleBadge: {
    display: "inline-block",
    borderRadius: "0.375rem",
    padding: "0.375rem 0.75rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "var(--color-white, #fff)",
    textTransform: "capitalize" as const,
  },
  statusBadge: {
    display: "inline-block",
    borderRadius: "0.375rem",
    padding: "0.375rem 0.75rem",
    fontSize: "0.875rem",
    fontWeight: "500",
    color: "var(--color-white, #fff)",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "0.75rem",
    flexShrink: 0,
  },
  detailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "1.5rem",
    margin: "1.5rem 0",
  },
  detailsItem: {
    marginBottom: "1rem",
  },
  detailsLabel: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
    marginBottom: "0.375rem",
    display: "flex",
    alignItems: "center",
  },
  detailsValue: {
    fontSize: "1rem",
    color: "var(--color-text, #333)",
    fontWeight: "500",
  },
  divider: {
    height: "1px",
    backgroundColor: "var(--color-grey-400, #ccc)",
    margin: "1.5rem 0",
  },
  formGroup: {
    marginBottom: "1.5rem",
  },
  label: {
    display: "block",
    fontSize: "1rem",
    color: "var(--color-text, #333)",
    fontWeight: "500",
    marginBottom: "0.5rem",
  },
  input: {
    width: "100%",
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    borderRadius: "0.375rem",
    outline: "none",
    transition: "border-color 0.2s, box-shadow 0.2s",
    "&:focus": {
      borderColor: "var(--color-blue, #1976d2)",
      boxShadow: "0 0 0 3px rgba(25, 118, 210, 0.1)",
    },
  },
  select: {
    width: "100%",
    padding: "0.75rem 1rem",
    fontSize: "1rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    borderRadius: "0.375rem",
    outline: "none",
    backgroundColor: "var(--color-white, #fff)",
    appearance: "none" as const,
    backgroundImage: `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='16' height='16' viewBox='0 0 24 24' fill='none' stroke='%23333' stroke-width='2' stroke-linecap='round' stroke-linejoin='round'%3E%3Cpolyline points='6 9 12 15 18 9'%3E%3C/polyline%3E%3C/svg%3E")`,
    backgroundRepeat: "no-repeat",
    backgroundPosition: "right 12px center",
    paddingRight: "2.5rem",
    transition: "border-color 0.2s, box-shadow 0.2s",
    "&:focus": {
      borderColor: "var(--color-blue, #1976d2)",
      boxShadow: "0 0 0 3px rgba(25, 118, 210, 0.1)",
    },
  },
  actionsContainer: {
    marginTop: "2rem",
    display: "flex",
    justifyContent: "flex-end",
    gap: "1rem",
  },
  noDataCard: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    padding: "2rem 1rem",
    color: "var(--color-grey-600, #666)",
    textAlign: "center" as const,
  },
  noDataIcon: {
    fontSize: "3rem",
    color: "var(--color-grey-500, #999)",
    marginBottom: "1rem",
  },
  noDataText: {
    fontSize: "1rem",
    marginBottom: "1rem",
    maxWidth: "20rem",
    margin: "0 auto",
  },
  companyCard: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    padding: "1rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    borderRadius: "0.375rem",
    marginBottom: "1rem",
    cursor: "pointer",
    transition: "background-color 0.2s, transform 0.1s",
    "&:hover": {
      backgroundColor: "var(--color-grey-100, #f8f9fa)",
      transform: "translateY(-2px)",
    },
  },
  companyLogo: {
    width: "3.125rem",
    height: "3.125rem",
    borderRadius: "0.375rem",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--color-grey-100, #f8f9fa)",
    color: "var(--color-blue, #1976d2)",
  },
  companyInfo: {
    flex: 1,
  },
  companyName: {
    fontSize: "1.125rem",
    fontWeight: "600",
    color: "var(--color-text, #333)",
    marginBottom: "0.25rem",
  },
  companyDetails: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
  },
  teamsList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "0.75rem",
    marginTop: "1rem",
  },
  teamItem: {
    display: "flex",
    alignItems: "center",
    gap: "1rem",
    padding: "0.875rem 1rem",
    borderRadius: "0.375rem",
    border: "1px solid var(--color-grey-400, #ccc)",
    cursor: "pointer",
    transition: "background-color 0.2s, transform 0.1s",
    "&:hover": {
      backgroundColor: "var(--color-grey-100, #f8f9fa)",
      transform: "translateY(-2px)",
    },
  },
  teamIcon: {
    color: "var(--color-blue, #1976d2)",
    fontSize: "1.25rem",
  },
  teamInfo: {
    flex: 1,
  },
  teamName: {
    fontSize: "1rem",
    fontWeight: "500",
    color: "var(--color-text, #333)",
    marginBottom: "0.25rem",
  },
  teamMemberCount: {
    fontSize: "0.875rem",
    color: "var(--color-grey-600, #666)",
  },
  leaderBadge: {
    fontSize: "0.75rem",
    color: "var(--color-white, #fff)",
    backgroundColor: "var(--color-blue, #1976d2)",
    padding: "0.25rem 0.5rem",
    borderRadius: "0.75rem",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
};
