import { CSSProperties } from "react";

export const authStyles: Record<string, CSSProperties> = {
  imageWrapper: {
    position: "relative",
    width: "90%",
    height: "97vh",
    borderRadius: "var(--border-big-radius)",
    overflow: "hidden",
    margin: "10px",
  },
  image: {
    objectFit: "cover",
    width: "100%",
    height: "100%",
    borderRadius: "var(--border-big-radius)",
  },
  logoWrapper: {
    position: "absolute",
    zIndex: 2,
  },
  logo: {
    objectFit: "contain",
    margin: "15px",
  },
  error: {
    color: "#ff4d4f",
    backgroundColor: "rgba(255, 77, 79, 0.1)",
    padding: "10px",
    borderRadius: "4px",
    marginBottom: "15px",
    textAlign: "center",
  },
  textWrapper: {
    position: "absolute",
    bottom: "80px",
    left: "0",
    background: "rgba(248, 248, 255, 0.1)",
    backdropFilter: "blur(10px)",
    padding: "var(--spacing-big) 32px",
    borderRadius: "0 var(--border-normal) var(--border-normal) 0",
    zIndex: 2,
  },
  title: {
    margin: 0,
    fontSize: "var(--font-size-title)",
    color: "rgba(248, 248, 255, 0.9)",
    fontWeight: "var(--font-weight-bold)",
    letterSpacing: "var(--text-letter-spacing)",
  },
  subtitle: {
    margin: "4px 0 0 0",
    color: "rgba(248, 248, 255, 0.7)",
    fontSize: "var(--font-size-small)",
    fontWeight: "var(--font-weight-regular)",
  },
  formContainer: {
    position: "absolute",
    right: "0",
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(42, 47, 53, 0.95)",
    padding: "48px 40px",
    width: "500px",
    borderRadius: "var(--border-big-radius) 0 0 var(--border-big-radius)",
    backdropFilter: "blur(10px)",
    boxShadow: "0 8px 32px rgba(0, 0, 0, 0.2)",
  },
  wrapper: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "var(--spacing-normal)",
  },
  form: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    gap: "var(--spacing-normal)",
    color: "var(--color-text)",
  },
  inputContainer: {
    width: "100%",
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  logoInput: {
    position: "absolute",
    left: "16px",
    zIndex: 2,
    opacity: "var(--opacity-less)",
  },
  input: {
    width: "100%",
    height: "46px",
    fontSize: "var(--font-size-normal)",
    padding: "0 44px",
    backgroundColor: "rgba(248, 248, 255, 0.08)",
    border: "var(--border-width) solid rgba(248, 248, 255, 0.1)",
    borderRadius: "var(--border-radius)",
    color: "var(--color-white)",
    outline: "none",
    transition: "var(--animation-transition)",
  },
  primaryButton: {
    width: "100%",
    height: "46px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    fontSize: "var(--font-size-normal)",
    fontWeight: "var(--font-weight-bold)",
    color: "var(--color-white)",
    backgroundColor: "var(--color-blue)",
    border: "none",
    borderRadius: "var(--border-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
    marginTop: "var(--spacing-small)",
  },
  loginOther: {
    width: "100%",
    textAlign: "center",
    color: "rgba(248, 248, 255, 0.4)",
    fontSize: "var(--font-size-small-small)",
    position: "relative",
    margin: "var(--spacing-normal) 0",
  },
  googleButton: {
    width: "100%",
    height: "46px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    gap: "10px",
    backgroundColor: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-radius)",
    cursor: "pointer",
    fontSize: "var(--font-size-normal)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-main)",
    transition: "var(--animation-transition)",
  },
};
