export const teamDetailStyles = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "var(--spacing-big)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "var(--spacing-big)",
  },
  backButton: {
    padding: "0.5rem 1rem",
    backgroundColor: "var(--color-neutral)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  title: {
    fontSize: "var(--font-size-title)",
    color: "var(--color-text)",
    marginBottom: "0.5rem",
  },
  description: {
    color: "var(--color-grey-600)",
    marginBottom: "var(--spacing-big)",
  },
  section: {
    marginBottom: "2.5rem",
  },
  sectionTitle: {
    fontSize: "var(--font-size-big)",
    color: "var(--color-text)",
    marginBottom: "1.2rem",
    display: "flex",
    alignItems: "center",
    borderBottom: "var(--border-width) solid var(--color-grey-400)",
    paddingBottom: "0.75rem",
  },
  sectionIcon: {
    marginRight: "0.75rem",
    color: "var(--color-blue)",
  },
  infoCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "1.5rem",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    marginBottom: "1.5rem",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
    gap: "1.5rem",
  },
  membersList: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "var(--spacing-normal)",
  },
  memberItem: {
    display: "flex",
    alignItems: "center",
    padding: "var(--spacing-normal)",
    borderRadius: "var(--border-radius)",
    backgroundColor: "var(--color-grey-100)",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  avatar: {
    width: "40px",
    height: "40px",
    borderRadius: "var(--border-circle-radius)",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: "var(--font-weight-bold)",
    marginRight: "var(--spacing-normal)",
  },
  memberInfo: {
    flexGrow: 1,
  },
  memberName: {
    fontWeight: "var(--font-weight-bold)",
    color: "var(--color-text)",
  },
  memberRole: {
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
  },
  leaderBadge: {
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    padding: "0.25rem 0.5rem",
    borderRadius: "var(--border-small-radius)",
    fontSize: "var(--font-size-small-small)",
    marginLeft: "auto",
  },
  clientsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(300px, 1fr))",
    gap: "1.5rem",
  },
  clientCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "1.5rem",
    boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
    display: "flex",
    flexDirection: "column" as const,
    height: "100%",
  },
  clientHeader: {
    display: "flex",
    alignItems: "center",
    marginBottom: "var(--spacing-normal)",
  },
  clientLogo: {
    width: "48px",
    height: "48px",
    borderRadius: "var(--border-radius)",
    backgroundColor: "var(--color-grey-100)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginRight: "var(--spacing-normal)",
  },
  clientName: {
    fontWeight: "var(--font-weight-bold)",
    fontSize: "var(--font-size-medium)",
    color: "var(--color-text)",
  },
  clientDescription: {
    color: "var(--color-grey-600)",
    marginBottom: "var(--spacing-normal)",
    flexGrow: 1,
  },
  clientDetails: {
    marginTop: "auto",
  },
  clientMeta: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    marginBottom: "0.5rem",
    color: "var(--color-grey-600)",
    fontSize: "var(--font-size-small)",
  },
  goodForCustomerBar: {
    width: "100%",
    height: "8px",
    backgroundColor: "var(--color-grey-300)",
    borderRadius: "var(--border-small-radius)",
    marginTop: "0.5rem",
    overflow: "hidden",
  },
  goodForCustomerFill: {
    height: "100%",
    backgroundColor: "var(--color-blue)",
    borderRadius: "var(--border-small-radius)",
  },
  viewDetailBtn: {
    width: "100%",
    padding: "0.75rem",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    marginTop: "var(--spacing-normal)",
    fontWeight: "var(--font-weight-medium)",
  },
  loadingSpinner: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "50vh",
    fontSize: "1.2rem",
    color: "var(--color-blue)",
  },
  errorMessage: {
    background: "var(--color-error-light)",
    color: "var(--color-error-dark)",
    padding: "var(--spacing-normal)",
    borderRadius: "var(--border-small-radius)",
    margin: "var(--spacing-big) auto",
    maxWidth: "800px",
    textAlign: "center" as const,
  },
};
