export const companyStyles = {
  container: {
    maxWidth: "1400px",
    margin: "0 auto",
    padding: "var(--spacing-big) var(--spacing-normal)",
  },
  pageTitle: {
    fontSize: "var(--font-size-big)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "30px",
    color: "var(--color-text)",
  },
  contentGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1.5fr",
    gap: "30px",
    alignItems: "start",
  },
  companyPanel: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "var(--spacing-normal)",
  },
  companyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  companyTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  companyInfoCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "25px",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.05)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "var(--spacing-normal)",
  },
  companyLogo: {
    width: "120px",
    height: "120px",
    objectFit: "contain" as const,
    margin: "0 auto var(--spacing-normal)",
    borderRadius: "var(--border-radius)",
  },
  companyLogoPlaceholder: {
    width: "120px",
    height: "120px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "var(--color-grey-100)",
    margin: "0 auto var(--spacing-normal)",
    borderRadius: "var(--border-radius)",
    color: "var(--color-blue)",
  },
  companyDetailsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: "var(--spacing-normal)",
  },
  detailItem: {
    display: "flex",
    flexDirection: "column" as const,
  },
  detailLabel: {
    fontWeight: "var(--font-weight-bold)",
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
    marginBottom: "5px",
  },
  detailValue: {
    fontSize: "var(--font-size-normal)",
    color: "var(--color-text)",
  },
  statusBadge: {
    display: "inline-block",
    borderRadius: "30px",
    padding: "5px 15px",
    fontSize: "var(--font-size-small)",
    fontWeight: "var(--font-weight-medium)",
    color: "var(--color-white)",
  },
  descriptionSection: {
    borderTop: "var(--border-width) solid var(--color-grey-400)",
    paddingTop: "var(--spacing-normal)",
    marginTop: "10px",
  },
  descriptionTitle: {
    fontSize: "var(--font-size-medium)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "10px",
    color: "var(--color-text)",
  },
  descriptionText: {
    fontSize: "var(--font-size-normal)",
    lineHeight: "var(--text-line-height)",
    color: "var(--color-grey-600)",
  },
  dataPanel: {
    display: "flex",
    flexDirection: "column" as const,
    gap: "25px",
  },
  sectionHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "10px",
  },
  sectionTitle: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  sectionIcon: {
    color: "var(--color-blue)",
    fontSize: "22px",
  },
  dataCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "var(--spacing-normal)",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.05)",
  },
  emptyState: {
    textAlign: "center" as const,
    padding: "30px 0",
    color: "var(--color-grey-600)",
  },
  teamsList: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
    gap: "var(--spacing-normal)",
  },
  teamCard: {
    padding: "15px",
    borderRadius: "var(--border-radius)",
    border: "var(--border-width) solid var(--color-grey-400)",
    transition: "var(--animation-transition)",
    display: "flex",
    flexDirection: "column" as const,
    gap: "10px",
  },
  teamCardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  teamName: {
    fontSize: "var(--font-size-normal)",
    fontWeight: "var(--font-weight-bold)",
    margin: 0,
  },
  memberCount: {
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
    backgroundColor: "var(--color-grey-100)",
    padding: "3px 8px",
    borderRadius: "20px",
  },
  teamDescription: {
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
    margin: "5px 0 10px",
    flexGrow: 1,
  },
  viewMoreCard: {
    padding: "15px",
    borderRadius: "var(--border-radius)",
    border: "1px dashed var(--color-grey-400)",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    justifyContent: "center",
    gap: "10px",
    color: "var(--color-grey-600)",
  },
  ellipsisIcon: {
    fontSize: "24px",
    color: "var(--color-blue)",
  },
  clientsTable: {
    width: "100%",
    borderCollapse: "collapse" as const,
    fontSize: "var(--font-size-small)",
  },
  tableHeader: {
    textAlign: "left" as const,
    padding: "12px 15px",
    borderBottom: "var(--border-width) solid var(--table-border)",
    color: "var(--color-grey-600)",
    fontWeight: "var(--font-weight-bold)",
  },
  tableRow: {
    borderBottom: "var(--border-width) solid var(--table-border)",
    transition: "var(--animation-transition)",
  },
  tableCell: {
    padding: "12px 15px",
  },
  tableCellActions: {
    padding: "8px 15px",
    textAlign: "right" as const,
  },
  viewMoreRow: {
    borderBottom: "none",
  },
  viewMoreCell: {
    padding: "15px",
  },
  viewMoreContent: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "var(--color-grey-600)",
  },
  noCompanyContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "60vh",
  },
  noCompanyCard: {
    background: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    padding: "40px",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.1)",
    textAlign: "center" as const,
    maxWidth: "500px",
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    gap: "var(--spacing-normal)",
  },
  noCompanyIcon: {
    fontSize: "60px",
    color: "var(--color-blue)",
  },
  noCompanyTitle: {
    fontSize: "var(--font-size-big)",
    fontWeight: "var(--font-weight-bold)",
    color: "var(--color-text)",
    margin: "10px 0",
  },
  noCompanyText: {
    fontSize: "var(--font-size-normal)",
    color: "var(--color-grey-600)",
    marginBottom: "var(--spacing-normal)",
  },
};
