export const clientFormStyles = {
  container: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    padding: "24px",
    marginBottom: "24px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: "32px",
  },
  title: {
    fontSize: "var(--font-size-big)",
    marginBottom: "var(--spacing-small)",
  },
  subTitle: {
    color: "var(--color-text)",
  },
  backButton: {
    padding: "10px 16px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  errorMessage: {
    backgroundColor: "#FEE2E2",
    color: "#DC2626",
    padding: "12px 16px",
    borderRadius: "6px",
    marginBottom: "24px",
    fontSize: "14px",
  },
  successMessage: {
    backgroundColor: "#DCFCE7",
    color: "#16A34A",
    padding: "12px 16px",
    borderRadius: "6px",
    marginBottom: "24px",
    fontSize: "14px",
  },
  section: {
    marginBottom: "var(--spacing-normal)",
  },
  sectionTitle: {
    fontSize: "24px",
    fontWeight: "600",
    color: "#333333",
    marginBottom: "24px",
    fontFamily: "var(--font-first)",
  },
  subsectionTitle: {
    fontSize: "var(--font-size-normal)",
    marginBottom: "12px",
  },
  formGroup: {
    marginBottom: "16px",
  },
  flexRow: {
    display: "flex",
    gap: "16px",
    marginBottom: "16px",
  },
  flexColumn: {
    flex: 1,
  },
  label: {
    display: "block",
    marginBottom: "var(--spacing-small)",
  },
  requiredField: {
    color: "var(--color-error-dark)",
  },
  input: {
    width: "100%",
    padding: "10px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    transition: "var(--animation-transition)",
  },
  textarea: {
    width: "100%",
    padding: "10px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    resize: "vertical" as const,
    transition: "var(--animation-transition)",
  },
  select: {
    width: "100%",
    padding: "10px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    transition: "var(--animation-transition)",
  },
  rangeInput: {
    width: "100%",
  },
  rangeLegend: {
    display: "flex",
    justifyContent: "space-between",
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "center",
  },
  checkbox: {
    marginRight: "var(--spacing-small)",
  },
  contactsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  addContactButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  noContactsMessage: {
    color: "var(--color-grey-600)",
    fontStyle: "italic",
  },
  maxContactsWarning: {
    color: "var(--color-warning)",
    marginBottom: "16px",
  },
  contactItem: {
    border: `var(--border-width) solid var(--color-grey-200)`,
    borderRadius: "var(--border-radius)",
    padding: "16px",
    marginBottom: "16px",
  },
  contactItemHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  contactItemTitle: {
    fontSize: "var(--font-size-normal)",
  },
  deleteContactButton: {
    padding: "4px 8px",
    backgroundColor: "var(--color-error-dark)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "space-between",
    marginTop: "32px",
    gap: "16px",
  },
  cancelButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-neutral)",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  submitButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    transition: "var(--animation-transition)",
  },
  loadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    minHeight: "200px",
    fontSize: "16px",
    color: "#666666",
  },
  errorContainer: {
    padding: "var(--spacing-normal)",
    color: "var(--color-error-dark)",
  },

  // Styles pour le stepper
  stepperContainer: {
    marginBottom: "40px",
  },
  stepperSteps: {
    display: "flex",
    justifyContent: "space-between",
    position: "relative" as const,
    marginBottom: "16px",
  },
  stepperLine: {
    position: "absolute" as const,
    top: "20px",
    left: "0",
    right: "0",
    height: "2px",
    backgroundColor: "#E0E0E0",
    zIndex: 1,
  },
  stepperStep: {
    display: "flex",
    flexDirection: "column" as const,
    alignItems: "center",
    position: "relative" as const,
    zIndex: 2,
  },
  stepperCircle: {
    width: "40px",
    height: "40px",
    borderRadius: "50%",
    backgroundColor: "#E0E0E0",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#666666",
    fontWeight: "600",
    marginBottom: "8px",
    border: "2px solid #E0E0E0",
  },
  stepperActiveCircle: {
    backgroundColor: "#A3B18A",
    color: "#ffffff",
    borderColor: "#A3B18A",
  },
  stepperCompletedCircle: {
    backgroundColor: "#2ECC71",
    color: "#ffffff",
    borderColor: "#2ECC71",
  },
  stepperLabel: {
    fontSize: "14px",
    color: "#666666",
    textAlign: "center" as const,
  },
  stepperActiveLabel: {
    color: "#A3B18A",
    fontWeight: "600",
  },
  stepperProgressBar: {
    height: "4px",
    backgroundColor: "#E0E0E0",
    borderRadius: "2px",
    overflow: "hidden",
  },
  stepperProgress: {
    height: "100%",
    backgroundColor: "#A3B18A",
    transition: "width 0.3s ease",
  },
  prevButton: {
    padding: "12px 24px",
    backgroundColor: "transparent",
    border: "1px solid #A3B18A",
    color: "#A3B18A",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "500",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "rgba(163, 177, 138, 0.1)",
    },
  },
  nextButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    transition: "var(--animation-transition)",
  },
  submitStepperButton: {
    padding: "12px 32px",
    backgroundColor: "#A3B18A",
    border: "none",
    color: "#ffffff",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "16px",
    fontWeight: "600",
    transition: "all 0.2s ease",
    "&:hover": {
      backgroundColor: "#8A9A6E",
    },
  },
  summaryContainer: {
    backgroundColor: "#ffffff",
    borderRadius: "8px",
    padding: "24px",
    marginBottom: "24px",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.1)",
  },
  summaryItem: {
    display: "flex",
    marginBottom: "12px",
    "&:last-child": {
      marginBottom: 0,
    },
  },
  summaryLabel: {
    width: "150px",
    color: "#666666",
    fontWeight: "500",
  },
  summaryValue: {
    flex: 1,
    color: "#333333",
  },
  summarySection: {
    marginBottom: "24px",
    "&:last-child": {
      marginBottom: 0,
    },
  },
  summarySectionTitle: {
    fontSize: "18px",
    fontWeight: "600",
    color: "#333333",
    marginBottom: "16px",
    fontFamily: "var(--font-first)",
  },
  summaryContactItem: {
    backgroundColor: "#F8FAFC",
    borderRadius: "6px",
    padding: "16px",
    marginBottom: "12px",
    "&:last-child": {
      marginBottom: 0,
    },
  },
  summaryPrimaryContact: {
    backgroundColor: "var(--color-success-light)",
    padding: "5px",
    marginTop: "5px",
    borderRadius: "var(--border-small-radius)",
    display: "inline-block",
    fontSize: "var(--font-size-small-small)",
  },
  navigationButton: {
    padding: "10px 20px",
    backgroundColor: "#4a90e2",
    color: "white",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "14px",
    margin: "0 10px",
    transition: "background-color 0.3s ease",
    "&:hover": {
      backgroundColor: "#357abd",
    },
  },
};
