export const clientFormStyles = {
  container: {
    padding: "var(--spacing-big)",
    borderRadius: "var(--border-radius)",
    boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
    marginBottom: "var(--spacing-big)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "var(--spacing-normal)",
  },
  title: {
    fontSize: "var(--font-size-big)",
    marginBottom: "var(--spacing-small)",
  },
  subTitle: {
    color: "var(--color-text)",
  },
  backButton: {
    padding: "10px 16px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  errorMessage: {
    padding: "12px",
    backgroundColor: "var(--color-error-light)",
    color: "var(--color-error-dark)",
    borderRadius: "var(--border-small-radius)",
    marginBottom: "var(--spacing-normal)",
  },
  successMessage: {
    padding: "12px",
    backgroundColor: "var(--color-success-light)",
    color: "var(--color-success-dark)",
    borderRadius: "var(--border-small-radius)",
    marginBottom: "var(--spacing-normal)",
  },
  section: {
    marginBottom: "var(--spacing-normal)",
  },
  sectionTitle: {
    fontSize: "var(--font-size-medium)",
    marginBottom: "16px",
  },
  subsectionTitle: {
    fontSize: "var(--font-size-normal)",
    marginBottom: "12px",
  },
  formGroup: {
    marginBottom: "16px",
  },
  flexRow: {
    display: "flex",
    gap: "16px",
    marginBottom: "16px",
  },
  flexColumn: {
    flex: 1,
  },
  label: {
    display: "block",
    marginBottom: "var(--spacing-small)",
  },
  requiredField: {
    color: "var(--color-error-dark)",
  },
  input: {
    width: "100%",
    padding: "10px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    transition: "var(--animation-transition)",
  },
  textarea: {
    width: "100%",
    padding: "10px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    resize: "vertical" as const,
    transition: "var(--animation-transition)",
  },
  select: {
    width: "100%",
    padding: "10px",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    transition: "var(--animation-transition)",
  },
  rangeInput: {
    width: "100%",
  },
  rangeLegend: {
    display: "flex",
    justifyContent: "space-between",
  },
  checkboxContainer: {
    display: "flex",
    alignItems: "center",
  },
  checkbox: {
    marginRight: "var(--spacing-small)",
  },
  contactsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
  },
  addContactButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  noContactsMessage: {
    color: "var(--color-grey-600)",
    fontStyle: "italic",
  },
  maxContactsWarning: {
    color: "var(--color-warning)",
    marginBottom: "16px",
  },
  contactItem: {
    border: `var(--border-width) solid var(--color-grey-200)`,
    borderRadius: "var(--border-radius)",
    padding: "16px",
    marginBottom: "16px",
  },
  contactItemHeader: {
    display: "flex",
    justifyContent: "space-between",
    marginBottom: "16px",
  },
  contactItemTitle: {
    fontSize: "var(--font-size-normal)",
  },
  deleteContactButton: {
    padding: "4px 8px",
    backgroundColor: "var(--color-error-dark)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  buttonContainer: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "16px",
    marginTop: "var(--spacing-big)",
  },
  cancelButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-neutral)",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  submitButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    transition: "var(--animation-transition)",
  },
  loadingContainer: {
    padding: "var(--spacing-normal)",
    backgroundColor: "var(--color-white)",
    borderRadius: "var(--border-radius)",
    boxShadow: "0 2px 10px rgba(0,0,0,0.1)",
    textAlign: "center" as "center",
  },
  errorContainer: {
    padding: "var(--spacing-normal)",
    color: "var(--color-error-dark)",
  },

  // Styles pour le stepper
  stepperContainer: {
    marginBottom: "30px",
  },
  stepperSteps: {
    display: "flex",
    justifyContent: "space-between",
    position: "relative" as "relative",
    marginBottom: "var(--spacing-normal)",
  },
  stepperStep: {
    display: "flex",
    flexDirection: "column" as "column",
    alignItems: "center",
    flex: 1,
  },
  stepperCircle: {
    width: "30px",
    height: "30px",
    borderRadius: "var(--border-circle-radius)",
    backgroundColor: "var(--color-grey-500)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: "10px",
    color: "var(--color-white)",
    fontWeight: "var(--font-weight-bold)",
    zIndex: 2,
  },
  stepperActiveCircle: {
    backgroundColor: "var(--color-blue)",
  },
  stepperCompletedCircle: {
    backgroundColor: "var(--color-success-dark)",
  },
  stepperLabel: {
    fontSize: "var(--font-size-small)",
    color: "var(--color-grey-600)",
    textAlign: "center" as "center",
  },
  stepperActiveLabel: {
    color: "var(--color-blue)",
    fontWeight: "var(--font-weight-bold)",
  },
  stepperLine: {
    position: "absolute" as "absolute",
    top: "15px",
    height: "2px",
    backgroundColor: "var(--color-grey-500)",
    zIndex: 1,
    left: "15%",
    right: "15%",
  },
  stepperProgressBar: {
    height: "6px",
    backgroundColor: "var(--color-grey-300)",
    borderRadius: "3px",
    margin: "var(--spacing-normal) 0",
    position: "relative" as "relative",
  },
  stepperProgress: {
    height: "100%",
    backgroundColor: "var(--color-blue)",
    borderRadius: "3px",
    transition: "width var(--animation-transition-time) ease",
  },
  prevButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-neutral)",
    border: `var(--border-width) solid var(--color-grey-400)`,
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    transition: "var(--animation-transition)",
  },
  nextButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-blue)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    transition: "var(--animation-transition)",
  },
  submitStepperButton: {
    padding: "10px 20px",
    backgroundColor: "var(--color-success-dark)",
    color: "var(--color-white)",
    border: "none",
    borderRadius: "var(--border-small-radius)",
    cursor: "pointer",
    fontWeight: "var(--font-weight-medium)",
    transition: "var(--animation-transition)",
  },
  summaryContainer: {
    backgroundColor: "var(--color-grey-100)",
    padding: "var(--spacing-normal)",
    borderRadius: "var(--border-radius)",
    marginBottom: "var(--spacing-normal)",
  },
  summaryItem: {
    display: "flex",
    marginBottom: "10px",
  },
  summaryLabel: {
    fontWeight: "var(--font-weight-bold)",
    width: "150px",
  },
  summaryValue: {
    flex: 1,
  },
  summarySection: {
    marginBottom: "var(--spacing-normal)",
  },
  summarySectionTitle: {
    fontSize: "var(--font-size-normal)",
    fontWeight: "var(--font-weight-bold)",
    marginBottom: "10px",
    borderBottom: `var(--border-width) solid var(--color-grey-400)`,
    paddingBottom: "5px",
  },
  summaryContactItem: {
    marginBottom: "10px",
    padding: "10px",
    backgroundColor: "var(--color-grey-200)",
    borderRadius: "var(--border-small-radius)",
  },
  summaryPrimaryContact: {
    backgroundColor: "var(--color-success-light)",
    padding: "5px",
    marginTop: "5px",
    borderRadius: "var(--border-small-radius)",
    display: "inline-block",
    fontSize: "var(--font-size-small-small)",
  },
};
